sudo: false
language: node_js
node_js: 
  - "node"
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm test
  - npm run build
deploy:
  provider: heroku
  app: image-gallery-shri
  api_key: 
    secure: "e92dba93-f6a1-4aca-8f09-f1e0db331c56"
