/**
 * Created by Sw_DOn on 24.03.2018.
 */
export default [
        {
            id:'1',
            path:'./img/img1.jpg',
            w:'1280',
            h:'900'
        },
        {
            id:'2',
            path:'./img/img2.jpg',
            w:1144,
            h:1144
        },
        {
            id:'3',
            path:'./img/img3-1.jpg',
            w:500,
            h:500
        },
        {
            id:'4',
            path:'./img/img4.jpg',
            w:500,
            h:412
        },
        {
            id:'5',
            path:'./img/img5.jpg',
            w:1240,
            h:775
        },
        {
            id:'6',
            path:'./img/img6.jpg',
            w:1568,
            h:1104
        },
        {
            id:'7',
            path:'./img/img7.jpg',
            w:1920,
            h:1080
        },
        {
            id:'9',
            path:'./img/img9.jpg',
            w:350,
            h:350
        },
        {
            id:'8',
            path:'./img/img8.jpg',
            w:500,
            h:367
        },

        {
            id:'10',
            path:'./img/img10.jpg',
            w:640,
            h:480
        }
    ]